apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secret
spec:
  vaultAuthRef: vault-auth
  mount: demo-kv
  type: kv-v2
  path: app/db
  refreshAfter: 30s
  destination:
    name: db-secret
    create: true
